Works on Mac, need to retest on Ubuntu

diff --git a/contrib/install b/contrib/install
--- a/contrib/install
+++ b/contrib/install
@@ -3,9 +3,16 @@
 # Only tested on Ubuntu 14.04
 
 # Uses information stored in GitBucket git repo on GitHub as defaults.
-# Edit gitbucket.conf before running this script
+# Edit gitbucket.conf before running this
+
+set -e
 
 GITBUCKET_VERSION=2.1
+
+if [ ! -f gitbucket.conf ]; then
+  echo "gitbucket.conf not found, aborting"
+  exit -3
+fi
 source gitbucket.conf
 
 function createDir {
@@ -14,11 +21,6 @@ function createDir {
     sudo mkdir -p "$1"
   fi
 }
-
-if [ ! -d "/etc/init.d/" ]; then
-  echo "/etc/init.d/ does not exist. This script requires System V init script compatibility."
-  exit -1
-fi
 
 if [ "$(which iptables)" ]; then
   echo "Opening port $GITBUCKET_PORT in firewall."
@@ -33,17 +35,30 @@ createDir "$GITBUCKET_LOG_DIR"
 echo "Fetching GitBucket v$GITBUCKET_VERSION and saving as $GITBUCKET_WAR_FILE"
 sudo wget -qO "$GITBUCKET_WAR_FILE" https://github.com/takezoe/gitbucket/releases/download/$GITBUCKET_VERSION/gitbucket.war
 
-# Install gitbucket as a service that starts when system boots
-sudo cp gitbucket.init "$GITBUCKET_SERVICE"
+sudo rm -f "$GITBUCKET_LOG_DIR/run.log"
+
 echo "Copying gitbucket.conf to $GITBUCKET_DIR"
 sudo cp gitbucket.conf $GITBUCKET_DIR
-sudo chown root:root $GITBUCKET_SERVICE
-sudo chmod 755 $GITBUCKET_SERVICE
-sudo update-rc.d $GITBUCKET_SERVICE defaults
+if [ `isUbuntu` ] || [ `isRedHat` ]; then
+  sudo cp gitbucket.init "$GITBUCKET_SERVICE"
+  # Install gitbucket as a service that starts when system boots
+  sudo chown root:root $GITBUCKET_SERVICE
+  sudo chmod 755 $GITBUCKET_SERVICE
+  sudo update-rc.d $GITBUCKET_SERVICE defaults
+  echo "Starting GitBucket service"
+  sudo $GITBUCKET_SERVICE start
+elif [ `isMac` ]; then
+  sudo macosx/makePlist
+  echo "Starting GitBucket service"
+  sudo cp gitbucket.conf "$GITBUCKET_SERVICE"
+  sudo cp gitbucket.init "$GITBUCKET_SERVICE"
+  sudo chmod a+x "$GITBUCKET_SERVICE"
+  sudo "$GITBUCKET_SERVICE" start
+else
+  echo "Don't know how to install this OS"
+  exit -2
+fi
 
-echo "Starting GitBucket service"
-sudo rm -f "$GITBUCKET_LOG_DIR/run.log"
-sudo $GITBUCKET_SERVICE start
 if [ $? != 0 ]; then
   less "$GITBUCKET_LOG_DIR/run.log"
 fi
